# Generated by Django 5.2.1 on 2025-07-08 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supportmessage',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='supportmessage',
            name='image',
        ),
        migrations.AddField(
            model_name='supportmessage',
            name='sender',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supportmessage',
            name='user_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
