# Generated by Django 5.2.1 on 2025-07-08 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_rename_created_at_supportmessage_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportmessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='support_images/'),
        ),
    ]
